///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace MyTest1
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the MyTest1Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("c5a597fd-db4d-4f86-a5c4-93ea1e5bcf39")]
    public partial class MyTest1Repository : RepoGenBaseFolder
    {
        static MyTest1Repository instance = new MyTest1Repository();
        MyTest1RepositoryFolders.GetPasswordAppFolder _getpassword;
        MyTest1RepositoryFolders.SetupOCM9999991AppFolder _setupocm9999991;
        MyTest1RepositoryFolders.SettingsOcm2AppFolder _settingsocm2;
        MyTest1RepositoryFolders.ConfirmerAppFolder _confirmer;

        /// <summary>
        /// Gets the singleton class instance representing the MyTest1Repository element repository.
        /// </summary>
        [RepositoryFolder("c5a597fd-db4d-4f86-a5c4-93ea1e5bcf39")]
        public static MyTest1Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public MyTest1Repository() 
            : base("MyTest1Repository", "/", null, 0, false, "c5a597fd-db4d-4f86-a5c4-93ea1e5bcf39", ".\\RepositoryImages\\MyTest1Repositoryc5a597fd.rximgres")
        {
            _getpassword = new MyTest1RepositoryFolders.GetPasswordAppFolder(this);
            _setupocm9999991 = new MyTest1RepositoryFolders.SetupOCM9999991AppFolder(this);
            _settingsocm2 = new MyTest1RepositoryFolders.SettingsOcm2AppFolder(this);
            _confirmer = new MyTest1RepositoryFolders.ConfirmerAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("c5a597fd-db4d-4f86-a5c4-93ea1e5bcf39")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The GetPassword folder.
        /// </summary>
        [RepositoryFolder("1da4a8a2-81ea-48c7-a6e8-22967a2654f8")]
        public virtual MyTest1RepositoryFolders.GetPasswordAppFolder GetPassword
        {
            get { return _getpassword; }
        }

        /// <summary>
        /// The SetupOCM9999991 folder.
        /// </summary>
        [RepositoryFolder("a9cf233c-bd98-4544-ae55-1d53be5027b2")]
        public virtual MyTest1RepositoryFolders.SetupOCM9999991AppFolder SetupOCM9999991
        {
            get { return _setupocm9999991; }
        }

        /// <summary>
        /// The SettingsOcm2 folder.
        /// </summary>
        [RepositoryFolder("42d4a7da-b71f-4526-ab91-b54b9c5715c7")]
        public virtual MyTest1RepositoryFolders.SettingsOcm2AppFolder SettingsOcm2
        {
            get { return _settingsocm2; }
        }

        /// <summary>
        /// The Confirmer folder.
        /// </summary>
        [RepositoryFolder("d0c0a652-0223-4609-86c1-bec6090dfdec")]
        public virtual MyTest1RepositoryFolders.ConfirmerAppFolder Confirmer
        {
            get { return _confirmer; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class MyTest1RepositoryFolders
    {
        /// <summary>
        /// The GetPasswordAppFolder folder.
        /// </summary>
        [RepositoryFolder("1da4a8a2-81ea-48c7-a6e8-22967a2654f8")]
        public partial class GetPasswordAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _textInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _buttonokInfo;

            /// <summary>
            /// Creates a new GetPassword  folder.
            /// </summary>
            public GetPasswordAppFolder(RepoGenBaseFolder parentFolder) :
                    base("GetPassword", "/form[@controlname='GetPassword']", parentFolder, 30000, null, true, "1da4a8a2-81ea-48c7-a6e8-22967a2654f8", "")
            {
                _textInfo = new RepoItemInfo(this, "Text", "container[@controlname='Panel1']/?/?/text[@accessiblerole='Text']", ".//text[@accessiblerole='Text']", 30000, null, "67cfeccc-ebed-4dd8-abdf-154a0de0f107");
                _passwordInfo = new RepoItemInfo(this, "Password", "?/?/text[@name='Password']", "?/?/text[@name='Password']", 30000, null, "32e1e373-62c9-4b04-9501-4962ac399033");
                _buttonokInfo = new RepoItemInfo(this, "ButtonOK", "?/?/button[@name='Btn_OK']", "?/?/button[@name='Btn_OK']", 30000, null, "9ed29ccc-7c38-4c3a-a1aa-ed5878fc0853");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1da4a8a2-81ea-48c7-a6e8-22967a2654f8")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1da4a8a2-81ea-48c7-a6e8-22967a2654f8")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("67cfeccc-ebed-4dd8-abdf-154a0de0f107")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("67cfeccc-ebed-4dd8-abdf-154a0de0f107")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("32e1e373-62c9-4b04-9501-4962ac399033")]
            public virtual Ranorex.Text Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("32e1e373-62c9-4b04-9501-4962ac399033")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The ButtonOK item.
            /// </summary>
            [RepositoryItem("9ed29ccc-7c38-4c3a-a1aa-ed5878fc0853")]
            public virtual Ranorex.Button ButtonOK
            {
                get
                {
                    return _buttonokInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOK item info.
            /// </summary>
            [RepositoryItemInfo("9ed29ccc-7c38-4c3a-a1aa-ed5878fc0853")]
            public virtual RepoItemInfo ButtonOKInfo
            {
                get
                {
                    return _buttonokInfo;
                }
            }
        }

        /// <summary>
        /// The SetupOCM9999991AppFolder folder.
        /// </summary>
        [RepositoryFolder("a9cf233c-bd98-4544-ae55-1d53be5027b2")]
        public partial class SetupOCM9999991AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _fermerInfo;

            /// <summary>
            /// Creates a new SetupOCM9999991  folder.
            /// </summary>
            public SetupOCM9999991AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SetupOCM9999991", "/form[@name='MainForm']", parentFolder, 30000, null, true, "a9cf233c-bd98-4544-ae55-1d53be5027b2", "")
            {
                _fermerInfo = new RepoItemInfo(this, "Fermer", "form[@name='MccCfgDlg']/?/?/button[@name='btnOK']", ".//button[@name='btnOK']", 30000, null, "16575fe4-1397-45f0-873d-a089d481dc5d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a9cf233c-bd98-4544-ae55-1d53be5027b2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a9cf233c-bd98-4544-ae55-1d53be5027b2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Fermer item.
            /// </summary>
            [RepositoryItem("16575fe4-1397-45f0-873d-a089d481dc5d")]
            public virtual Ranorex.Button Fermer
            {
                get
                {
                    return _fermerInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Fermer item info.
            /// </summary>
            [RepositoryItemInfo("16575fe4-1397-45f0-873d-a089d481dc5d")]
            public virtual RepoItemInfo FermerInfo
            {
                get
                {
                    return _fermerInfo;
                }
            }
        }

        /// <summary>
        /// The SettingsOcm2AppFolder folder.
        /// </summary>
        [RepositoryFolder("42d4a7da-b71f-4526-ab91-b54b9c5715c7")]
        public partial class SettingsOcm2AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _configurationInfo;
            RepoItemInfo _quitterInfo;

            /// <summary>
            /// Creates a new SettingsOcm2  folder.
            /// </summary>
            public SettingsOcm2AppFolder(RepoGenBaseFolder parentFolder) :
                    base("SettingsOcm2", "/contextmenu[@processname='SettingsOcm 2']", parentFolder, 30000, null, false, "42d4a7da-b71f-4526-ab91-b54b9c5715c7", "")
            {
                _configurationInfo = new RepoItemInfo(this, "Configuration", "?/?/menuitem[@accessiblename='Configuration...']", "?/?/menuitem[@accessiblename='Configuration...']", 30000, null, "9ab1e35e-7ef0-4d2f-a375-07c5f7a42efb");
                _quitterInfo = new RepoItemInfo(this, "Quitter", "?/?/menuitem[@accessiblename='Quitter']", "?/?/menuitem[@accessiblename='Quitter']", 30000, null, "81464635-6128-45f5-b096-7c61e0cd2d6b");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("42d4a7da-b71f-4526-ab91-b54b9c5715c7")]
            public virtual Ranorex.ContextMenu Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.ContextMenu>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("42d4a7da-b71f-4526-ab91-b54b9c5715c7")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Configuration item.
            /// </summary>
            [RepositoryItem("9ab1e35e-7ef0-4d2f-a375-07c5f7a42efb")]
            public virtual Ranorex.MenuItem Configuration
            {
                get
                {
                    return _configurationInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Configuration item info.
            /// </summary>
            [RepositoryItemInfo("9ab1e35e-7ef0-4d2f-a375-07c5f7a42efb")]
            public virtual RepoItemInfo ConfigurationInfo
            {
                get
                {
                    return _configurationInfo;
                }
            }

            /// <summary>
            /// The Quitter item.
            /// </summary>
            [RepositoryItem("81464635-6128-45f5-b096-7c61e0cd2d6b")]
            public virtual Ranorex.MenuItem Quitter
            {
                get
                {
                    return _quitterInfo.CreateAdapter<Ranorex.MenuItem>(true);
                }
            }

            /// <summary>
            /// The Quitter item info.
            /// </summary>
            [RepositoryItemInfo("81464635-6128-45f5-b096-7c61e0cd2d6b")]
            public virtual RepoItemInfo QuitterInfo
            {
                get
                {
                    return _quitterInfo;
                }
            }
        }

        /// <summary>
        /// The ConfirmerAppFolder folder.
        /// </summary>
        [RepositoryFolder("d0c0a652-0223-4609-86c1-bec6090dfdec")]
        public partial class ConfirmerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _buttonouiInfo;

            /// <summary>
            /// Creates a new Confirmer  folder.
            /// </summary>
            public ConfirmerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Confirmer", "/form[@name='none']", parentFolder, 30000, null, true, "d0c0a652-0223-4609-86c1-bec6090dfdec", "")
            {
                _buttonouiInfo = new RepoItemInfo(this, "ButtonOui", "button[@name='Yes']", "button[@name='Yes']", 30000, null, "0bffadfe-e1e1-4b23-9c6f-733b3aa76e76");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d0c0a652-0223-4609-86c1-bec6090dfdec")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d0c0a652-0223-4609-86c1-bec6090dfdec")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ButtonOui item.
            /// </summary>
            [RepositoryItem("0bffadfe-e1e1-4b23-9c6f-733b3aa76e76")]
            public virtual Ranorex.Button ButtonOui
            {
                get
                {
                    return _buttonouiInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The ButtonOui item info.
            /// </summary>
            [RepositoryItemInfo("0bffadfe-e1e1-4b23-9c6f-733b3aa76e76")]
            public virtual RepoItemInfo ButtonOuiInfo
            {
                get
                {
                    return _buttonouiInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
